default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: rails-ci-testing-and-deployment-to-ec2-capistrano_development

test:
  <<: *default
  database: rails-ci-testing-and-deployment-to-ec2-capistrano_test

production:
  <<: *default
  database: rails-ci-testing-and-deployment-to-ec2-capistrano_production
  username: cgibsonmm
  password: cg359997
  host: localhost
  port: 5432
