# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4989496c87cddef275d48b1242a3e9222e60924815e203f7e549f9b1fa270efd35e10415593af9a8dfc6abb3bf06ed9c44f207b15d4b3cdcafa17b150ed82cb

test:
  secret_key_base: ca816aaaf1781301a65b19dfe5f129b7fbaf2771da07b6cdfed596e49dff61077d6b7c734d995577a6a2dedd96e5088489807df997633dd61a47ef79cb8768ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
